import { Lexicon } from "./types";
import { PAST_PARTICIPLE_ADJECTIVES } from "./pastParticipleAdjectives";

export const LEXICON: Lexicon = {
  markers: {
    "marker.time.today": {
      meaningKey: "marker.time.today",
      gup: "",
      pos: "adverb",
      breaksObjectWindow: true,
      timeRole: "today",
      formsByLang: {
        es: ["hoy", "ahora", "esta noche"],
        en: ["today", "now", "tonight", "this evening"],
      },
    },
    "marker.time.yesterday": {
      meaningKey: "marker.time.yesterday",
      gup: "barpuru",
      pos: "adverb",
      breaksObjectWindow: true,
      timeRole: "yesterday",
      formsByLang: {
        es: ["ayer", "anoche"],
        en: ["yesterday", "last night"],
      },
    },
    "marker.time.future": {
      meaningKey: "marker.time.future",
      gup: "",
      pos: "adverb",
      breaksObjectWindow: true,
      timeRole: "future",
      formsByLang: {
        es: [
          "mañana",
          "manana",
          "próximo",
          "próxima",
          "proximo",
          "proxima",
          "después",
          "despues",
          "luego",
          "pronto",
          "la próxima semana",
          "la proxima semana",
          "el próximo mes",
          "el proximo mes",
          "el próximo año",
          "el proximo ano",
          "dentro de",
          "en un",
          "en una",
        ],
        en: [
          "tomorrow",
          "next",
          "later",
          "soon",
          "next week",
          "next month",
          "next year",
          "in a",
        ],
      },
    },
    "marker.time.tomorrow": {
      meaningKey: "marker.time.tomorrow",
      gup: "goḏarr'",
      pos: "adverb",
      breaksObjectWindow: true,
      timeRole: "future",
      formsByLang: {
        es: ["mañana", "manana"],
        en: ["tomorrow"],
      },
    },
    "marker.time.later": {
      meaningKey: "marker.time.later",
      gup: "yalala",
      pos: "adverb",
      breaksObjectWindow: true,
      formsByLang: {
        es: ["más tarde", "mas tarde"],
        en: ["later", "later on"],
      },
    },
    "marker.time.afternoon": {
      meaningKey: "marker.time.afternoon",
      gup: "milmitjpa",
      pos: "adverb",
      breaksObjectWindow: true,
      formsByLang: {
        es: ["la tarde", "esta noche"],
        en: ["this afternoon", "this evening"],
      },
    },
    "marker.time.sometime": {
      meaningKey: "marker.time.sometime",
      gup: "babalamirri",
      pos: "adverb",
      breaksObjectWindow: true,
      formsByLang: {
        es: ["en algún momento", "en algun momento", "pronto"],
        en: ["sometime", "anytime"],
      },
    },
    "marker.time.again": {
      meaningKey: "marker.time.again",
      gup: "bulu",
      pos: "adverb",
      breaksObjectWindow: true,
      formsByLang: {
        es: ["de nuevo", "más", "mas"],
        en: ["again", "more"],
      },
    },
    "marker.time.straight-away": {
      meaningKey: "marker.time.straight-away",
      gup: "dhunupana bala",
      pos: "adverb",
      breaksObjectWindow: true,
      formsByLang: {
        es: ["pronto"],
        en: ["straight away"],
      },
    },
    "marker.motion.away": {
      meaningKey: "marker.motion.away",
      gup: "bala",
      pos: "adverb",
      tags: ["no-allative-suffix"],
      locationRole: "motion",
      formsByLang: {
        es: [
          "por allá",
          "por alla",
          "por ahí",
          "por ahi",
          "para allá",
          "para alla",
          "hacia allá",
          "hacia alla",
        ],
        en: ["that way"],
      },
    },
    "marker.motion.toward": {
      meaningKey: "marker.motion.toward",
      gup: "räli",
      pos: "adverb",
      tags: ["no-allative-suffix"],
      locationRole: "motion",
      formsByLang: {
        es: [
          "por aquí",
          "por aqui",
          "por acá",
          "por aca",
          "para aquí",
          "para aqui",
          "para acá",
          "para aca",
          "hacia aquí",
          "hacia aqui",
          "hacia acá",
          "hacia aca",
        ],
        en: ["this way"],
      },
    },
    "marker.locative.inside": {
      meaningKey: "marker.locative.inside",
      gup: "djinaga",
      pos: "adverb",
      breaksObjectWindow: true,
      locationRole: "stationary",
      formsByLang: {
        es: ["dentro", "adentro"],
        en: ["inside"],
      },
    },
    "marker.locative.outside": {
      meaningKey: "marker.locative.outside",
      gup: "warraŋul",
      pos: "adverb",
      breaksObjectWindow: true,
      locationRole: "stationary",
      formsByLang: {
        es: ["fuera", "afuera"],
        en: ["outside"],
      },
    },
    "marker.locative.far": {
      meaningKey: "marker.locative.far",
      gup: "barrku",
      pos: "adverb",
      breaksObjectWindow: true,
      locationRole: "stationary",
      formsByLang: {
        es: ["lejos"],
        en: ["far", "far away"],
      },
    },
    "marker.locative.close": {
      meaningKey: "marker.locative.close",
      gup: "galki",
      pos: "adverb",
      breaksObjectWindow: true,
      locationRole: "stationary",
      formsByLang: {
        es: ["cerca"],
        en: ["close", "near"],
      },
    },
    "marker.locative.above": {
      meaningKey: "marker.locative.above",
      gup: "garrwar",
      pos: "adverb",
      breaksObjectWindow: true,
      locationRole: "stationary",
      formsByLang: {
        es: ["arriba", "encima", "sobre"],
        en: ["above", "over", "on top of"],
      },
    },
  },
  nouns: {
    "ŋula yol": {
      meaningKey: "noun.ŋula-yol",
      gup: "ŋula yol",
      pos: "noun",
      plurals: [],
      isHuman: true,
      formsByLang: {
        es: ["alguien"],
        en: ["anyone"],
      },
      pluralFormsByLang: {
        es: ["algunos"],
        en: ["some people"],
      },
    },
    bakthun: {
      meaningKey: "noun.bakthun",
      gup: "bakthun",
      pos: "noun",
      plurals: [],
      isHuman: false,
      formsByLang: {
        es: ["accidente"],
        en: ["accident"],
      },
      pluralFormsByLang: {
        es: ["accidentes"],
        en: ["accidents"],
      },
    },
    gapu: {
      meaningKey: "noun.gapu",
      gup: "gapu",
      pos: "noun",
      plurals: [],
      isHuman: false,
      formsByLang: {
        es: ["agua"],
        en: ["water"],
      },
      pluralFormsByLang: {
        es: ["aguas"],
        en: ["waters"],
      },
    },
    "ŋatha": {
      meaningKey: "noun.ŋatha",
      gup: "ŋatha",
      pos: "noun",
      plurals: [],
      isHuman: false,
      formsByLang: {
        es: ["comida"],
        en: ["food"],
      },
      pluralFormsByLang: {
        es: ["comidas"],
        en: ["foods"],
      },
    },
    wäŋa: {
      meaningKey: "noun.wäŋa",
      gup: "wäŋa",
      pos: "noun",
      plurals: [],
      isHuman: false,
      isPlace: true,
      formsByLang: {
        es: ["casa", "hogar", "lugar"],
        en: ["house", "home", "place"],
      },
      pluralFormsByLang: {
        es: ["casas", "hogares", "lugares"],
        en: ["houses", "homes", "places"],
      },
    },
    "new york": {
      meaningKey: "noun.new-york",
      gup: "new york",
      pos: "noun",
      plurals: [],
      isPlace: true,
      isHuman: false,
      formsByLang: {
        es: ["New York", "Nueva York"],
        en: ["New York"],
      },
      pluralFormsByLang: {
        es: ["New Yorks"],
        en: ["New Yorks"],
      },
    },
  },
  verbs: {
    ḻuka: {
      meaningKey: "verb.ḻuka",
      gup: "ḻuka",
      pos: "verb",
      verbGroup: 3,
      gupForms: ["ḻuka", "ḻuki", "ḻukana", "ḻukanha", "ḻukanhara"],
      plurals: [],
      isTransitive: true,
      isPlural: false,
      conjugations: {
        es: [
          {
            infinitive: "comer",
            presentIndicative: [
              "como",
              "comes",
              "come",
              "comemos",
              "coméis",
              "comen",
            ],
            preterite: [
              "comí",
              "comiste",
              "comió",
              "comimos",
              "comisteis",
              "comieron",
            ],
            imperfect: [
              "comía",
              "comías",
              "comía",
              "comíamos",
              "comíais",
              "comían",
            ],
            future: [
              "comeré",
              "comerás",
              "comerá",
              "comeremos",
              "comeréis",
              "comerán",
            ],
            conditional: [
              "comería",
              "comerías",
              "comería",
              "comeríamos",
              "comeríais",
              "comerían",
            ],
            presentSubjunctive: [
              "coma",
              "comas",
              "coma",
              "comamos",
              "comáis",
              "coman",
            ],
            imperfectSubjunctive: [
              "comiera",
              "comieras",
              "comiera",
              "comiéramos",
              "comierais",
              "comieran",
            ],
            imperative: {
              tu: "come",
              usted: "coma",
              nosotros: "comamos",
              vosotros: "comed",
              ustedes: "coman",
            },
            negativeImperative: {
              tu: "no comas",
              usted: "no coma",
              nosotros: "no comamos",
              vosotros: "no comáis",
              ustedes: "no coman",
            },
            gerund: "comiendo",
            pastParticiple: "comido",
          },
          {
            infinitive: "beber",
            presentIndicative: [
              "bebo",
              "bebes",
              "bebe",
              "bebemos",
              "bebéis",
              "beben",
            ],
            preterite: [
              "bebí",
              "bebiste",
              "bebió",
              "bebimos",
              "bebisteis",
              "bebieron",
            ],
            imperfect: [
              "bebía",
              "bebías",
              "bebía",
              "bebíamos",
              "bebíais",
              "bebían",
            ],
            future: [
              "beberé",
              "beberás",
              "beberá",
              "beberemos",
              "beberéis",
              "beberán",
            ],
            conditional: [
              "bebería",
              "beberías",
              "bebería",
              "beberíamos",
              "beberíais",
              "beberían",
            ],
            presentSubjunctive: [
              "beba",
              "bebas",
              "beba",
              "bebamos",
              "bebáis",
              "beban",
            ],
            imperfectSubjunctive: [
              "bebiera",
              "bebieras",
              "bebiera",
              "bebiéramos",
              "bebierais",
              "bebieran",
            ],
            imperative: {
              tu: "bebe",
              usted: "beba",
              nosotros: "bebamos",
              vosotros: "bebed",
              ustedes: "beban",
            },
            negativeImperative: {
              tu: "no bebas",
              usted: "no beba",
              nosotros: "no bebamos",
              vosotros: "no bebáis",
              ustedes: "no beban",
            },
            gerund: "bebiendo",
            pastParticiple: "bebido",
          },
          {
            infinitive: "consumir",
            presentIndicative: [
              "consumo",
              "consumes",
              "consume",
              "consumimos",
              "consumís",
              "consumen",
            ],
            preterite: [
              "consumí",
              "consumiste",
              "consumió",
              "consumimos",
              "consumisteis",
              "consumieron",
            ],
            imperfect: [
              "consumía",
              "consumías",
              "consumía",
              "consumíamos",
              "consumíais",
              "consumían",
            ],
            future: [
              "consumiré",
              "consumirás",
              "consumirá",
              "consumiremos",
              "consumiréis",
              "consumirán",
            ],
            conditional: [
              "consumiría",
              "consumirías",
              "consumiría",
              "consumiríamos",
              "consumiríais",
              "consumirían",
            ],
            presentSubjunctive: [
              "consuma",
              "consumas",
              "consuma",
              "consumamos",
              "consumáis",
              "consuman",
            ],
            imperfectSubjunctive: [
              "consumiera",
              "consumieras",
              "consumiera",
              "consumiéramos",
              "consumierais",
              "consumieran",
            ],
            imperative: {
              tu: "consume",
              usted: "consuma",
              nosotros: "consumamos",
              vosotros: "consumid",
              ustedes: "consuman",
            },
            negativeImperative: {
              tu: "no consumas",
              usted: "no consuma",
              nosotros: "no consumamos",
              vosotros: "no consumáis",
              ustedes: "no consuman",
            },
            gerund: "consumiendo",
            pastParticiple: "consumido",
          },
        ],
        en: [
          {
            infinitive: "eat",
            presentIndicative: ["eat", "eat", "eats", "eat", "eat", "eat"],
            preterite: ["ate", "ate", "ate", "ate", "ate", "ate"],
            imperfect: [
              "was eating",
              "were eating",
              "was eating",
              "were eating",
              "were eating",
              "were eating",
            ],
            future: [
              "will eat",
              "will eat",
              "will eat",
              "will eat",
              "will eat",
              "will eat",
            ],
            conditional: [
              "would eat",
              "would eat",
              "would eat",
              "would eat",
              "would eat",
              "would eat",
            ],
            presentSubjunctive: ["eat", "eat", "eat", "eat", "eat", "eat"],
            imperative: {
              tu: "eat",
              usted: "eat",
              nosotros: "let's eat",
              vosotros: "eat",
              ustedes: "eat",
            },
            negativeImperative: {
              tu: "don't eat",
              usted: "don't eat",
              nosotros: "let's not eat",
              vosotros: "don't eat",
              ustedes: "don't eat",
            },
            gerund: "eating",
            pastParticiple: "eaten",
          },
          {
            infinitive: "drink",
            presentIndicative: [
              "drink",
              "drink",
              "drinks",
              "drink",
              "drink",
              "drink",
            ],
            preterite: ["drank", "drank", "drank", "drank", "drank", "drank"],
            imperfect: [
              "was drinking",
              "were drinking",
              "was drinking",
              "were drinking",
              "were drinking",
              "were drinking",
            ],
            future: [
              "will drink",
              "will drink",
              "will drink",
              "will drink",
              "will drink",
              "will drink",
            ],
            conditional: [
              "would drink",
              "would drink",
              "would drink",
              "would drink",
              "would drink",
              "would drink",
            ],
            presentSubjunctive: [
              "drink",
              "drink",
              "drink",
              "drink",
              "drink",
              "drink",
            ],
            imperative: {
              tu: "drink",
              usted: "drink",
              nosotros: "let's drink",
              vosotros: "drink",
              ustedes: "drink",
            },
            negativeImperative: {
              tu: "don't drink",
              usted: "don't drink",
              nosotros: "let's not drink",
              vosotros: "don't drink",
              ustedes: "don't drink",
            },
            gerund: "drinking",
            pastParticiple: "drunk",
          },
          {
            infinitive: "consume",
            presentIndicative: [
              "consume",
              "consume",
              "consumes",
              "consume",
              "consume",
              "consume",
            ],
            preterite: [
              "consumed",
              "consumed",
              "consumed",
              "consumed",
              "consumed",
              "consumed",
            ],
            imperfect: [
              "was consuming",
              "were consuming",
              "was consuming",
              "were consuming",
              "were consuming",
              "were consuming",
            ],
            future: [
              "will consume",
              "will consume",
              "will consume",
              "will consume",
              "will consume",
              "will consume",
            ],
            conditional: [
              "would consume",
              "would consume",
              "would consume",
              "would consume",
              "would consume",
              "would consume",
            ],
            presentSubjunctive: [
              "consume",
              "consume",
              "consume",
              "consume",
              "consume",
              "consume",
            ],
            imperative: {
              tu: "consume",
              usted: "consume",
              nosotros: "let's consume",
              vosotros: "consume",
              ustedes: "consume",
            },
            negativeImperative: {
              tu: "don't consume",
              usted: "don't consume",
              nosotros: "let's not consume",
              vosotros: "don't consume",
              ustedes: "don't consume",
            },
            gerund: "consuming",
            pastParticiple: "consumed",
          },
        ],
      },
      derived: {
        pastParticipleAdjectives: {
          es: [
            "comido",
            "comida",
            "comidos",
            "comidas",
            "bebido",
            "bebida",
            "bebidos",
            "bebidas",
            "consumido",
            "consumida",
            "consumidos",
            "consumidas",
          ],
          en: ["eaten", "drunk", "consumed"],
        },
        verbalNouns: {
          es: [
            "comida",
            "comidas",
            "consumo",
            "consumos",
            "ingesta",
            "ingestas",
            "bebida",
            "bebidas",
          ],
          en: [
            "food",
            "foods",
            "meal",
            "meals",
            "consumption",
            "consumptions",
            "drink",
            "drinks",
            "intake",
            "intakes",
          ],
        },
        agentNouns: {
          es: ["comedor", "comedora", "comedores", "comedoras"],
          en: ["eater", "eaters"],
        },
        relatedNouns: {
          es: [
            "comida",
            "comidas",
            "bebida",
            "bebidas",
            "alimento",
            "alimentos",
            "agua",
            "aguas",
          ],
          en: [
            "food",
            "foods",
            "drink",
            "drinks",
            "meal",
            "meals",
            "water",
            "waters",
          ],
        },
        relatedAdjectives: {
          es: [
            "comestible",
            "comestibles",
            "bebible",
            "bebibles",
            "alimenticio",
            "alimenticia",
            "alimenticios",
            "alimenticias",
          ],
          en: ["edible", "drinkable", "nutritious"],
        },
      },
    },
    "mala-buma": {
      meaningKey: "verb.mala-buma",
      gup: "mala-buma",
      pos: "verb",
      verbGroup: 9,
      gupForms: ["mala-buma", "mala-buŋu", "mala-bumara", "mala-bunha"],
      plurals: [],
      isTransitive: true,
      isPlural: false,
      isHaveVerb: true,
      conjugations: {
        es: [
          {
            infinitive: "tener",
            presentIndicative: [
              "tengo",
              "tienes",
              "tiene",
              "tenemos",
              "tenéis",
              "tienen",
            ],
            preterite: [
              "tuve",
              "tuviste",
              "tuvo",
              "tuvimos",
              "tuvisteis",
              "tuvieron",
            ],
            imperfect: [
              "tenía",
              "tenías",
              "tenía",
              "teníamos",
              "teníais",
              "tenían",
            ],
            future: [
              "tendré",
              "tendrás",
              "tendrá",
              "tendremos",
              "tendréis",
              "tendrán",
            ],
            conditional: [
              "tendría",
              "tendrías",
              "tendría",
              "tendríamos",
              "tendríais",
              "tendrían",
            ],
            presentSubjunctive: [
              "tenga",
              "tengas",
              "tenga",
              "tengamos",
              "tengáis",
              "tengan",
            ],
            imperfectSubjunctive: [
              "tuviera",
              "tuvieras",
              "tuviera",
              "tuviéramos",
              "tuvierais",
              "tuvieran",
            ],
            imperative: {
              tu: "ten",
              usted: "tenga",
              nosotros: "tengamos",
              vosotros: "tened",
              ustedes: "tengan",
            },
            negativeImperative: {
              tu: "no tengas",
              usted: "no tenga",
              nosotros: "no tengamos",
              vosotros: "no tengáis",
              ustedes: "no tengan",
            },
            gerund: "teniendo",
            pastParticiple: "tenido",
          },
          {
            infinitive: "poseer",
            presentIndicative: [
              "poseo",
              "posees",
              "posee",
              "poseemos",
              "poseéis",
              "poseen",
            ],
            preterite: [
              "poseí",
              "poseíste",
              "poseyó",
              "poseímos",
              "poseísteis",
              "poseyeron",
            ],
            imperfect: [
              "poseía",
              "poseías",
              "poseía",
              "poseíamos",
              "poseíais",
              "poseían",
            ],
            future: [
              "poseeré",
              "poseerás",
              "poseerá",
              "poseeremos",
              "poseeréis",
              "poseerán",
            ],
            conditional: [
              "poseería",
              "poseerías",
              "poseería",
              "poseeríamos",
              "poseeríais",
              "poseerían",
            ],
            presentSubjunctive: [
              "posea",
              "poseas",
              "posea",
              "poseamos",
              "poseáis",
              "posean",
            ],
            imperfectSubjunctive: [
              "poseyera",
              "poseyeras",
              "poseyera",
              "poseyéramos",
              "poseyerais",
              "poseyeran",
            ],
            imperative: {
              tu: "posee",
              usted: "posea",
              nosotros: "poseamos",
              vosotros: "poseed",
              ustedes: "posean",
            },
            negativeImperative: {
              tu: "no poseas",
              usted: "no posea",
              nosotros: "no poseamos",
              vosotros: "no poseáis",
              ustedes: "no posean",
            },
            gerund: "poseyendo",
            pastParticiple: "poseído",
          },
          {
            infinitive: "pertenecer",
            presentIndicative: [
              "pertenezco",
              "perteneces",
              "pertenece",
              "pertenecemos",
              "pertenecéis",
              "pertenecen",
            ],
            preterite: [
              "pertenecí",
              "perteneciste",
              "perteneció",
              "pertenecimos",
              "pertenecisteis",
              "pertenecieron",
            ],
            imperfect: [
              "pertenecía",
              "pertenecías",
              "pertenecía",
              "pertenecíamos",
              "pertenecíais",
              "pertenecían",
            ],
            future: [
              "perteneceré",
              "pertenecerás",
              "pertenecerá",
              "perteneceremos",
              "perteneceréis",
              "pertenecerán",
            ],
            conditional: [
              "pertenecería",
              "pertenecerías",
              "pertenecería",
              "perteneceríamos",
              "perteneceríais",
              "pertenecerían",
            ],
            presentSubjunctive: [
              "pertenezca",
              "pertenezcas",
              "pertenezca",
              "pertenezcamos",
              "pertenezcáis",
              "pertenezcan",
            ],
            imperfectSubjunctive: [
              "perteneciera",
              "pertenecieras",
              "perteneciera",
              "perteneciéramos",
              "pertenecierais",
              "pertenecieran",
            ],
            imperative: {
              tu: "pertenece",
              usted: "pertenezca",
              nosotros: "pertenezcamos",
              vosotros: "perteneced",
              ustedes: "pertenezcan",
            },
            negativeImperative: {
              tu: "no pertenezcas",
              usted: "no pertenezca",
              nosotros: "no pertenezcamos",
              vosotros: "no pertenezcáis",
              ustedes: "no pertenezcan",
            },
            gerund: "perteneciendo",
            pastParticiple: "pertenecido",
          },
          {
            infinitive: "carecer",
            presentIndicative: [
              "carezco",
              "careces",
              "carece",
              "carecemos",
              "carecéis",
              "carecen",
            ],
            preterite: [
              "carecí",
              "careciste",
              "careció",
              "carecimos",
              "carecisteis",
              "carecieron",
            ],
            imperfect: [
              "carecía",
              "carecías",
              "carecía",
              "carecíamos",
              "carecíais",
              "carecían",
            ],
            future: [
              "careceré",
              "carecerás",
              "carecerá",
              "careceremos",
              "careceréis",
              "carecerán",
            ],
            conditional: [
              "carecería",
              "carecerías",
              "carecería",
              "careceríamos",
              "careceríais",
              "carecerían",
            ],
            presentSubjunctive: [
              "carezca",
              "carezcas",
              "carezca",
              "carezcamos",
              "carezcáis",
              "carezcan",
            ],
            imperfectSubjunctive: [
              "careciera",
              "carecieras",
              "careciera",
              "careciéramos",
              "carecierais",
              "carecieran",
            ],
            imperative: {
              tu: "carece",
              usted: "carezca",
              nosotros: "carezcamos",
              vosotros: "careced",
              ustedes: "carezcan",
            },
            negativeImperative: {
              tu: "no carezcas",
              usted: "no carezca",
              nosotros: "no carezcamos",
              vosotros: "no carezcáis",
              ustedes: "no carezcan",
            },
            gerund: "careciendo",
            pastParticiple: "carecido",
          },
        ],
        en: [
          {
            infinitive: "have",
            presentIndicative: ["have", "have", "has", "have", "have", "have"],
            preterite: ["had", "had", "had", "had", "had", "had"],
            imperfect: [
              "was having",
              "were having",
              "was having",
              "were having",
              "were having",
              "were having",
            ],
            future: [
              "will have",
              "will have",
              "will have",
              "will have",
              "will have",
              "will have",
            ],
            conditional: [
              "would have",
              "would have",
              "would have",
              "would have",
              "would have",
              "would have",
            ],
            presentSubjunctive: [
              "have",
              "have",
              "have",
              "have",
              "have",
              "have",
            ],
            imperative: {
              tu: "have",
              usted: "have",
              nosotros: "let's have",
              vosotros: "have",
              ustedes: "have",
            },
            negativeImperative: {
              tu: "don't have",
              usted: "don't have",
              nosotros: "let's not have",
              vosotros: "don't have",
              ustedes: "don't have",
            },
            gerund: "having",
            pastParticiple: "had",
          },
          {
            infinitive: "have got",
            presentIndicative: [
              "have got",
              "have got",
              "has got",
              "have got",
              "have got",
              "have got",
            ],
            preterite: [
              "had got",
              "had got",
              "had got",
              "had got",
              "had got",
              "had got",
            ],
            imperfect: [
              "was having got",
              "were having got",
              "was having got",
              "were having got",
              "were having got",
              "were having got",
            ],
            future: [
              "will have got",
              "will have got",
              "will have got",
              "will have got",
              "will have got",
              "will have got",
            ],
            conditional: [
              "would have got",
              "would have got",
              "would have got",
              "would have got",
              "would have got",
              "would have got",
            ],
            presentSubjunctive: [
              "have got",
              "have got",
              "have got",
              "have got",
              "have got",
              "have got",
            ],
            imperative: {
              tu: "have got",
              usted: "have got",
              nosotros: "let's have got",
              vosotros: "have got",
              ustedes: "have got",
            },
            negativeImperative: {
              tu: "don't have got",
              usted: "don't have got",
              nosotros: "let's not have got",
              vosotros: "don't have got",
              ustedes: "don't have got",
            },
            gerund: "having got",
            pastParticiple: "had got",
          },
          {
            infinitive: "possess",
            presentIndicative: [
              "possess",
              "possess",
              "possesses",
              "possess",
              "possess",
              "possess",
            ],
            preterite: [
              "possessed",
              "possessed",
              "possessed",
              "possessed",
              "possessed",
              "possessed",
            ],
            imperfect: [
              "was possessing",
              "were possessing",
              "was possessing",
              "were possessing",
              "were possessing",
              "were possessing",
            ],
            future: [
              "will possess",
              "will possess",
              "will possess",
              "will possess",
              "will possess",
              "will possess",
            ],
            conditional: [
              "would possess",
              "would possess",
              "would possess",
              "would possess",
              "would possess",
              "would possess",
            ],
            presentSubjunctive: [
              "possess",
              "possess",
              "possess",
              "possess",
              "possess",
              "possess",
            ],
            imperative: {
              tu: "possess",
              usted: "possess",
              nosotros: "let's possess",
              vosotros: "possess",
              ustedes: "possess",
            },
            negativeImperative: {
              tu: "don't possess",
              usted: "don't possess",
              nosotros: "let's not possess",
              vosotros: "don't possess",
              ustedes: "don't possess",
            },
            gerund: "possessing",
            pastParticiple: "possessed",
          },
          {
            infinitive: "own",
            presentIndicative: ["own", "own", "owns", "own", "own", "own"],
            preterite: ["owned", "owned", "owned", "owned", "owned", "owned"],
            imperfect: [
              "was owning",
              "were owning",
              "was owning",
              "were owning",
              "were owning",
              "were owning",
            ],
            future: [
              "will own",
              "will own",
              "will own",
              "will own",
              "will own",
              "will own",
            ],
            conditional: [
              "would own",
              "would own",
              "would own",
              "would own",
              "would own",
              "would own",
            ],
            presentSubjunctive: ["own", "own", "own", "own", "own", "own"],
            imperative: {
              tu: "own",
              usted: "own",
              nosotros: "let's own",
              vosotros: "own",
              ustedes: "own",
            },
            negativeImperative: {
              tu: "don't own",
              usted: "don't own",
              nosotros: "let's not own",
              vosotros: "don't own",
              ustedes: "don't own",
            },
            gerund: "owning",
            pastParticiple: "owned",
          },
          {
            infinitive: "belong",
            presentIndicative: [
              "belong",
              "belong",
              "belongs",
              "belong",
              "belong",
              "belong",
            ],
            preterite: [
              "belonged",
              "belonged",
              "belonged",
              "belonged",
              "belonged",
              "belonged",
            ],
            imperfect: [
              "was belonging",
              "were belonging",
              "was belonging",
              "were belonging",
              "were belonging",
              "were belonging",
            ],
            future: [
              "will belong",
              "will belong",
              "will belong",
              "will belong",
              "will belong",
              "will belong",
            ],
            conditional: [
              "would belong",
              "would belong",
              "would belong",
              "would belong",
              "would belong",
              "would belong",
            ],
            presentSubjunctive: [
              "belong",
              "belong",
              "belong",
              "belong",
              "belong",
              "belong",
            ],
            imperative: {
              tu: "belong",
              usted: "belong",
              nosotros: "let's belong",
              vosotros: "belong",
              ustedes: "belong",
            },
            negativeImperative: {
              tu: "don't belong",
              usted: "don't belong",
              nosotros: "let's not belong",
              vosotros: "don't belong",
              ustedes: "don't belong",
            },
            gerund: "belonging",
            pastParticiple: "belonged",
          },
        ],
      },
    },
    marrtji: {
      meaningKey: "verb.marrtji",
      gup: "marrtji",
      pos: "verb",
      verbGroup: 2,
      gupForms: [
        "marrtji",
        "marrtji",
        "marrtjina",
        "marrtjinya",
        "marrtjinyara",
      ],
      plurals: [],
      isTransitive: false,
      isPlural: false,
      motionType: "motion",
      conjugations: {
        es: [
          {
            infinitive: "ir",
            presentIndicative: ["voy", "vas", "va", "vamos", "vais", "van"],
            preterite: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
            imperfect: ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
            future: ["iré", "irás", "irá", "iremos", "iréis", "irán"],
            conditional: [
              "iría",
              "irías",
              "iría",
              "iríamos",
              "iríais",
              "irían",
            ],
            presentSubjunctive: [
              "vaya",
              "vayas",
              "vaya",
              "vayamos",
              "vayáis",
              "vayan",
            ],
            imperfectSubjunctive: [
              "fuera",
              "fueras",
              "fuera",
              "fuéramos",
              "fuerais",
              "fueran",
            ],
            imperative: {
              tu: "ve",
              usted: "vaya",
              nosotros: "vayamos|vamos|vámonos|vamonos",
              vosotros: "id",
              ustedes: "vayan",
            },
            gerund: "yendo",
            pastParticiple: "ido",
          },
          {
            infinitive: "caminar",
            presentIndicative: [
              "camino",
              "caminas",
              "camina",
              "caminamos",
              "camináis",
              "caminan",
            ],
            preterite: [
              "caminé",
              "caminaste",
              "caminó",
              "caminamos",
              "caminasteis",
              "caminaron",
            ],
            imperfect: [
              "caminaba",
              "caminabas",
              "caminaba",
              "caminábamos",
              "caminabais",
              "caminaban",
            ],
            future: [
              "caminaré",
              "caminarás",
              "caminará",
              "caminaremos",
              "caminaréis",
              "caminarán",
            ],
            conditional: [
              "caminaría",
              "caminarías",
              "caminaría",
              "caminaríamos",
              "caminaríais",
              "caminarían",
            ],
            presentSubjunctive: [
              "camine",
              "camines",
              "camine",
              "caminemos",
              "caminéis",
              "caminen",
            ],
            imperfectSubjunctive: [
              "caminara",
              "caminaras",
              "caminara",
              "camináramos",
              "caminarais",
              "caminaran",
            ],
            imperative: {
              tu: "camina",
              usted: "camine",
              nosotros: "caminemos",
              vosotros: "caminad",
              ustedes: "caminen",
            },
            gerund: "caminando",
            pastParticiple: "caminado",
          },
          {
            infinitive: "continuar",
            presentIndicative: [
              "continúo",
              "continúas",
              "continúa",
              "continuamos",
              "continuáis",
              "continúan",
            ],
            preterite: [
              "continué",
              "continuaste",
              "continuó",
              "continuamos",
              "continuasteis",
              "continuaron",
            ],
            imperfect: [
              "continuaba",
              "continuabas",
              "continuaba",
              "continuábamos",
              "continuabais",
              "continuaban",
            ],
            future: [
              "continuaré",
              "continuarás",
              "continuará",
              "continuaremos",
              "continuaréis",
              "continuarán",
            ],
            conditional: [
              "continuaría",
              "continuarías",
              "continuaría",
              "continuaríamos",
              "continuaríais",
              "continuarían",
            ],
            presentSubjunctive: [
              "continúe",
              "continúes",
              "continúe",
              "continuemos",
              "continuéis",
              "continúen",
            ],
            imperfectSubjunctive: [
              "continuara",
              "continuaras",
              "continuara",
              "continuáramos",
              "continuarais",
              "continuaran",
            ],
            imperative: {
              tu: "continúa",
              usted: "continúe",
              nosotros: "continuemos",
              vosotros: "continuad",
              ustedes: "continúen",
            },
            gerund: "continuando",
            pastParticiple: "continuado",
          },
        ],
        en: [
          {
            infinitive: "go",
            presentIndicative: ["go", "go", "goes", "go", "go", "go"],
            preterite: ["went", "went", "went", "went", "went", "went"],
            imperfect: [
              "was going",
              "were going",
              "was going",
              "were going",
              "were going",
              "were going",
            ],
            future: [
              "will go",
              "will go",
              "will go",
              "will go",
              "will go",
              "will go",
            ],
            conditional: [
              "would go",
              "would go",
              "would go",
              "would go",
              "would go",
              "would go",
            ],
            presentSubjunctive: ["go", "go", "go", "go", "go", "go"],
            imperative: {
              tu: "go",
              usted: "go",
              nosotros: "let's go",
              vosotros: "go",
              ustedes: "go",
            },
            gerund: "going",
            pastParticiple: "gone",
          },
          {
            infinitive: "walk",
            presentIndicative: [
              "walk",
              "walk",
              "walks",
              "walk",
              "walk",
              "walk",
            ],
            preterite: [
              "walked",
              "walked",
              "walked",
              "walked",
              "walked",
              "walked",
            ],
            imperfect: [
              "was walking",
              "were walking",
              "was walking",
              "were walking",
              "were walking",
              "were walking",
            ],
            future: [
              "will walk",
              "will walk",
              "will walk",
              "will walk",
              "will walk",
              "will walk",
            ],
            conditional: [
              "would walk",
              "would walk",
              "would walk",
              "would walk",
              "would walk",
              "would walk",
            ],
            presentSubjunctive: [
              "walk",
              "walk",
              "walk",
              "walk",
              "walk",
              "walk",
            ],
            imperative: {
              tu: "walk",
              usted: "walk",
              nosotros: "let's walk",
              vosotros: "walk",
              ustedes: "walk",
            },
            gerund: "walking",
            pastParticiple: "walked",
          },
          {
            infinitive: "continue an activity",
            presentIndicative: [
              "continue",
              "continue",
              "continues",
              "continue",
              "continue",
              "continue",
            ],
            preterite: [
              "continued",
              "continued",
              "continued",
              "continued",
              "continued",
              "continued",
            ],
            imperfect: [
              "was continuing",
              "were continuing",
              "was continuing",
              "were continuing",
              "were continuing",
              "were continuing",
            ],
            future: [
              "will continue",
              "will continue",
              "will continue",
              "will continue",
              "will continue",
              "will continue",
            ],
            conditional: [
              "would continue",
              "would continue",
              "would continue",
              "would continue",
              "would continue",
              "would continue",
            ],
            presentSubjunctive: [
              "continue",
              "continue",
              "continue",
              "continue",
              "continue",
              "continue",
            ],
            imperative: {
              tu: "continue",
              usted: "continue",
              nosotros: "let's continue",
              vosotros: "continue",
              ustedes: "continue",
            },
            gerund: "continuing",
            pastParticiple: "continued",
          },
        ],
      },
      derived: {
        pastParticipleAdjectives: {
          es: [
            "ido",
            "ida",
            "idos",
            "idas",
            "caminado",
            "caminada",
            "caminados",
            "caminadas",
            "continuado",
            "continuada",
            "continuados",
            "continuadas",
          ],
          en: ["gone", "walked", "continued"],
        },
        verbalNouns: {
          es: [
            "ida",
            "idas",
            "viaje",
            "viajes",
            "caminata",
            "caminatas",
            "camino",
            "caminos",
            "marcha",
            "marchas",
            "continuación",
            "continuaciones",
            "movimiento",
            "movimientos",
          ],
          en: [
            "walk",
            "walks",
            "journey",
            "journeys",
            "trip",
            "trips",
            "continuation",
            "continuations",
            "movement",
            "movements",
          ],
        },
        agentNouns: {
          es: ["viajero", "viajera", "viajeros", "viajeras"],
          en: ["traveler", "travelers"],
        },
        relatedNouns: {
          es: [
            "camino",
            "caminos",
            "viaje",
            "viajes",
            "paseo",
            "paseos",
            "salida",
            "salidas",
            "trayecto",
            "trayectos",
            "continuación",
            "continuaciones",
            "movimiento",
            "movimientos",
          ],
          en: [
            "walk",
            "walks",
            "journey",
            "journeys",
            "trip",
            "trips",
            "outing",
            "outings",
            "route",
            "routes",
            "continuation",
            "continuations",
            "movement",
            "movements",
          ],
        },
        relatedAdjectives: {
          es: ["continuado", "continuada", "continuos", "continuas"],
          en: ["continuous", "ongoing"],
        },
      },
    },
    nhina: {
      meaningKey: "verb.nhina",
      gup: "nhina",
      pos: "verb",
      verbGroup: 3,
      gupForms: ["nhina", "nhini", "nhinana", "nhinanha"],
      plurals: [],
      isTransitive: false,
      isPlural: false,
      motionType: "stationary",
      conjugations: {
        es: [
          {
            infinitive: "sentarse",
            presentIndicative: [
              "me siento",
              "te sientas",
              "se sienta",
              "nos sentamos",
              "os sentáis",
              "se sientan",
            ],
            preterite: [
              "me senté",
              "te sentaste",
              "se sentó",
              "nos sentamos",
              "os sentasteis",
              "se sentaron",
            ],
            imperfect: [
              "me sentaba",
              "te sentabas",
              "se sentaba",
              "nos sentábamos",
              "os sentabais",
              "se sentaban",
            ],
            future: [
              "me sentaré",
              "te sentarás",
              "se sentará",
              "nos sentaremos",
              "os sentaréis",
              "se sentarán",
            ],
            conditional: [
              "me sentaría",
              "te sentarías",
              "se sentaría",
              "nos sentaríamos",
              "os sentaríais",
              "se sentarían",
            ],
            presentSubjunctive: [
              "me siente",
              "te sientes",
              "se siente",
              "nos sentemos",
              "os sentéis",
              "se sienten",
            ],
            imperfectSubjunctive: [
              "se sentara",
              "se sentaras",
              "se sentara",
              "se sentáramos",
              "se sentarais",
              "se sentaran",
            ],
            imperative: {
              tu: "siéntate",
              usted: "siéntese",
              nosotros: "sentémonos",
              vosotros: "sentaos",
              ustedes: "siéntense",
            },
            gerund: "sentándose",
            pastParticiple: "sentado",
          },
          {
            infinitive: "sentar",
            presentIndicative: [
              "siento",
              "sientas",
              "sienta",
              "sentamos",
              "sentáis",
              "sientan",
            ],
            preterite: [
              "senté",
              "sentaste",
              "sentó",
              "sentamos",
              "sentasteis",
              "sentaron",
            ],
            imperfect: [
              "sentaba",
              "sentabas",
              "sentaba",
              "sentábamos",
              "sentabais",
              "sentaban",
            ],
            future: [
              "sentaré",
              "sentarás",
              "sentará",
              "sentaremos",
              "sentaréis",
              "sentarán",
            ],
            conditional: [
              "sentaría",
              "sentarías",
              "sentaría",
              "sentaríamos",
              "sentaríais",
              "sentarían",
            ],
            presentSubjunctive: [
              "siente",
              "sientes",
              "siente",
              "sentemos",
              "sentéis",
              "sienten",
            ],
            imperfectSubjunctive: [
              "sentara",
              "sentaras",
              "sentara",
              "sentáramos",
              "sentarais",
              "sentaran",
            ],
            imperative: {
              tu: "sienta",
              usted: "siente",
              nosotros: "sentemos",
              vosotros: "sentad",
              ustedes: "sienten",
            },
            gerund: "sentando",
            pastParticiple: "sentado",
          },
        ],
        en: [
          {
            infinitive: "sit",
            presentIndicative: ["sit", "sit", "sits", "sit", "sit", "sit"],
            preterite: ["sat", "sat", "sat", "sat", "sat", "sat"],
            imperfect: [
              "was sitting",
              "were sitting",
              "was sitting",
              "were sitting",
              "were sitting",
              "were sitting",
            ],
            future: [
              "will sit",
              "will sit",
              "will sit",
              "will sit",
              "will sit",
              "will sit",
            ],
            conditional: [
              "would sit",
              "would sit",
              "would sit",
              "would sit",
              "would sit",
              "would sit",
            ],
            presentSubjunctive: ["sit", "sit", "sit", "sit", "sit", "sit"],
            imperative: {
              tu: "sit",
              usted: "sit",
              nosotros: "let's sit",
              vosotros: "sit",
              ustedes: "sit",
            },
            gerund: "sitting",
            pastParticiple: "sat",
          },
          {
            infinitive: "seat",
            presentIndicative: [
              "seat",
              "seat",
              "seats",
              "seat",
              "seat",
              "seat",
            ],
            preterite: [
              "seated",
              "seated",
              "seated",
              "seated",
              "seated",
              "seated",
            ],
            imperfect: [
              "was seating",
              "were seating",
              "was seating",
              "were seating",
              "were seating",
              "were seating",
            ],
            future: [
              "will seat",
              "will seat",
              "will seat",
              "will seat",
              "will seat",
              "will seat",
            ],
            conditional: [
              "would seat",
              "would seat",
              "would seat",
              "would seat",
              "would seat",
              "would seat",
            ],
            presentSubjunctive: [
              "seat",
              "seat",
              "seat",
              "seat",
              "seat",
              "seat",
            ],
            imperative: {
              tu: "seat",
              usted: "seat",
              nosotros: "let's seat",
              vosotros: "seat",
              ustedes: "seat",
            },
            gerund: "seating",
            pastParticiple: "seated",
          },
        ],
      },
    },
    dhärra: {
      meaningKey: "verb.dhärra",
      gup: "dhärra",
      pos: "verb",
      verbGroup: 3,
      gupForms: ["dhärra", "dhärri", "dhärrana", "dhärranha"],
      plurals: [],
      isTransitive: false,
      isPlural: false,
      motionType: "stationary",
      conjugations: {
        es: [
          {
            infinitive: "estar de pie",
            presentIndicative: [
              "estoy de pie",
              "estás de pie",
              "está de pie",
              "estamos de pie",
              "estáis de pie",
              "están de pie",
            ],
            preterite: [
              "estuve de pie",
              "estuviste de pie",
              "estuvo de pie",
              "estuvimos de pie",
              "estuvisteis de pie",
              "estuvieron de pie",
            ],
            imperfect: [
              "estaba de pie",
              "estabas de pie",
              "estaba de pie",
              "estábamos de pie",
              "estabais de pie",
              "estaban de pie",
            ],
            future: [
              "estaré de pie",
              "estarás de pie",
              "estará de pie",
              "estaremos de pie",
              "estaréis de pie",
              "estarán de pie",
            ],
            conditional: [
              "estaría de pie",
              "estarías de pie",
              "estaría de pie",
              "estaríamos de pie",
              "estaríais de pie",
              "estarían de pie",
            ],
            presentSubjunctive: [
              "esté de pie",
              "estés de pie",
              "esté de pie",
              "estemos de pie",
              "estéis de pie",
              "estén de pie",
            ],
            imperfectSubjunctive: [
              "estuviera de pie",
              "estuvieras de pie",
              "estuviera de pie",
              "estuviéramos de pie",
              "estuvierais de pie",
              "estuvieran de pie",
            ],
            imperative: {
              tu: "está de pie",
              usted: "esté de pie",
              nosotros: "estemos de pie",
              vosotros: "estad de pie",
              ustedes: "estén de pie",
            },
            gerund: "estando de pie",
            pastParticiple: "estado de pie",
          },
          {
            infinitive: "permanecer",
            presentIndicative: [
              "permanezco",
              "permaneces",
              "permanece",
              "permanecemos",
              "permanecéis",
              "permanecen",
            ],
            preterite: [
              "permanecí",
              "permaneciste",
              "permaneció",
              "permanecimos",
              "permanecisteis",
              "permanecieron",
            ],
            imperfect: [
              "permanecía",
              "permanecías",
              "permanecía",
              "permanecíamos",
              "permanecíais",
              "permanecían",
            ],
            future: [
              "permaneceré",
              "permanecerás",
              "permanecerá",
              "permaneceremos",
              "permaneceréis",
              "permanecerán",
            ],
            conditional: [
              "permanecería",
              "permanecerías",
              "permanecería",
              "permaneceríamos",
              "permaneceríais",
              "permanecerían",
            ],
            presentSubjunctive: [
              "permanezca",
              "permanezcas",
              "permanezca",
              "permanezcamos",
              "permanezcáis",
              "permanezcan",
            ],
            imperfectSubjunctive: [
              "permaneciera",
              "permanecieras",
              "permaneciera",
              "permaneciéramos",
              "permanecierais",
              "permanecieran",
            ],
            imperative: {
              tu: "permanece",
              usted: "permanezca",
              nosotros: "permanezcamos",
              vosotros: "permaneced",
              ustedes: "permanezcan",
            },
            gerund: "permaneciendo",
            pastParticiple: "permanecido",
          },
        ],
        en: [
          {
            infinitive: "stand",
            presentIndicative: [
              "stand",
              "stand",
              "stands",
              "stand",
              "stand",
              "stand",
            ],
            preterite: ["stood", "stood", "stood", "stood", "stood", "stood"],
            imperfect: [
              "was standing",
              "were standing",
              "was standing",
              "were standing",
              "were standing",
              "were standing",
            ],
            future: [
              "will stand",
              "will stand",
              "will stand",
              "will stand",
              "will stand",
              "will stand",
            ],
            conditional: [
              "would stand",
              "would stand",
              "would stand",
              "would stand",
              "would stand",
              "would stand",
            ],
            presentSubjunctive: [
              "stand",
              "stand",
              "stand",
              "stand",
              "stand",
              "stand",
            ],
            imperative: {
              tu: "stand",
              usted: "stand",
              nosotros: "let's stand",
              vosotros: "stand",
              ustedes: "stand",
            },
            gerund: "standing",
            pastParticiple: "stood",
          },
          {
            infinitive: "be (trees, boats etc.)",
            presentIndicative: ["am", "are", "is", "are", "are", "are"],
            preterite: ["was", "were", "was", "were", "were", "were"],
            imperfect: [
              "was being",
              "were being",
              "was being",
              "were being",
              "were being",
              "were being",
            ],
            future: [
              "will be",
              "will be",
              "will be",
              "will be",
              "will be",
              "will be",
            ],
            conditional: [
              "would be",
              "would be",
              "would be",
              "would be",
              "would be",
              "would be",
            ],
            presentSubjunctive: ["be", "be", "be", "be", "be", "be"],
            imperative: {
              tu: "be",
              usted: "be",
              nosotros: "let's be",
              vosotros: "be",
              ustedes: "be",
            },
            gerund: "being",
            pastParticiple: "been",
          },
        ],
      },
    },
    ŋorra: {
      meaningKey: "verb.ŋorra",
      gup: "ŋorra",
      pos: "verb",
      verbGroup: 3,
      gupForms: ["ŋorra", "ŋorri", "ŋorrana", "ŋorranha"],
      plurals: [],
      isTransitive: false,
      isPlural: false,
      motionType: "stationary",
      conjugations: {
        es: [
          {
            infinitive: "dormir",
            presentIndicative: [
              "duermo",
              "duermes",
              "duerme",
              "dormimos",
              "dormís",
              "duermen",
            ],
            preterite: [
              "dormí",
              "dormiste",
              "durmió",
              "dormimos",
              "dormisteis",
              "durmieron",
            ],
            imperfect: [
              "dormía",
              "dormías",
              "dormía",
              "dormíamos",
              "dormíais",
              "dormían",
            ],
            future: [
              "dormiré",
              "dormirás",
              "dormirá",
              "dormiremos",
              "dormiréis",
              "dormirán",
            ],
            conditional: [
              "dormiría",
              "dormirías",
              "dormiría",
              "dormiríamos",
              "dormiríais",
              "dormirían",
            ],
            presentSubjunctive: [
              "duerma",
              "duermas",
              "duerma",
              "durmamos",
              "durmáis",
              "duerman",
            ],
            imperfectSubjunctive: [
              "durmiera",
              "durmieras",
              "durmiera",
              "durmiéramos",
              "durmierais",
              "durmieran",
            ],
            imperative: {
              tu: "duerme",
              usted: "duerma",
              nosotros: "durmamos",
              vosotros: "dormid",
              ustedes: "duerman",
            },
            gerund: "durmiendo",
            pastParticiple: "dormido",
          },
          {
            infinitive: "acostarse",
            presentIndicative: [
              "me acuesto",
              "te acuestas",
              "se acuesta",
              "nos acostamos",
              "os acostáis",
              "se acuestan",
            ],
            preterite: [
              "me acosté",
              "te acostaste",
              "se acostó",
              "nos acostamos",
              "os acostasteis",
              "se acostaron",
            ],
            imperfect: [
              "me acostaba",
              "te acostabas",
              "se acostaba",
              "nos acostábamos",
              "os acostabais",
              "se acostaban",
            ],
            future: [
              "me acostaré",
              "te acostarás",
              "se acostará",
              "nos acostaremos",
              "os acostaréis",
              "se acostarán",
            ],
            conditional: [
              "me acostaría",
              "te acostarías",
              "se acostaría",
              "nos acostaríamos",
              "os acostaríais",
              "se acostarían",
            ],
            presentSubjunctive: [
              "me acueste",
              "te acuestes",
              "se acueste",
              "nos acostemos",
              "os acostéis",
              "se acuesten",
            ],
            imperfectSubjunctive: [
              "se acostara",
              "se acostaras",
              "se acostara",
              "se acostáramos",
              "se acostarais",
              "se acostaran",
            ],
            imperative: {
              tu: "acuéstate",
              usted: "acuéstese",
              nosotros: "acostémonos",
              vosotros: "acostaos",
              ustedes: "acuéstense",
            },
            gerund: "acostándose",
            pastParticiple: "acostado",
          },
          {
            infinitive: "vivir",
            presentIndicative: [
              "vivo",
              "vives",
              "vive",
              "vivimos",
              "vivís",
              "viven",
            ],
            preterite: [
              "viví",
              "viviste",
              "vivió",
              "vivimos",
              "vivisteis",
              "vivieron",
            ],
            imperfect: [
              "vivía",
              "vivías",
              "vivía",
              "vivíamos",
              "vivíais",
              "vivían",
            ],
            future: [
              "viviré",
              "vivirás",
              "vivirá",
              "viviremos",
              "viviréis",
              "vivirán",
            ],
            conditional: [
              "viviría",
              "vivirías",
              "viviría",
              "viviríamos",
              "viviríais",
              "vivirían",
            ],
            presentSubjunctive: [
              "viva",
              "vivas",
              "viva",
              "vivamos",
              "viváis",
              "vivan",
            ],
            imperfectSubjunctive: [
              "viviera",
              "vivieras",
              "viviera",
              "viviéramos",
              "vivierais",
              "vivieran",
            ],
            imperative: {
              tu: "vive",
              usted: "viva",
              nosotros: "vivamos",
              vosotros: "vivid",
              ustedes: "vivan",
            },
            gerund: "viviendo",
            pastParticiple: "vivido",
          },
          {
            infinitive: "yacer",
            presentIndicative: [
              "yazco",
              "yaces",
              "yace",
              "yacemos",
              "yacéis",
              "yacen",
            ],
            preterite: [
              "yací",
              "yaciste",
              "yació",
              "yacimos",
              "yacisteis",
              "yacieron",
            ],
            imperfect: [
              "yacía",
              "yacías",
              "yacía",
              "yacíamos",
              "yacíais",
              "yacían",
            ],
            future: [
              "yaceré",
              "yacerás",
              "yacerá",
              "yaceremos",
              "yaceréis",
              "yacerán",
            ],
            conditional: [
              "yacería",
              "yacerías",
              "yacería",
              "yaceríamos",
              "yaceríais",
              "yacerían",
            ],
            presentSubjunctive: [
              "yazca",
              "yazcas",
              "yazca",
              "yazcamos",
              "yazcáis",
              "yazcan",
            ],
            imperfectSubjunctive: [
              "yaciera",
              "yacieras",
              "yaciera",
              "yaciéramos",
              "yacierais",
              "yacieran",
            ],
            imperative: {
              tu: "yace",
              usted: "yazca",
              nosotros: "yazcamos",
              vosotros: "yaced",
              ustedes: "yazcan",
            },
            gerund: "yaciendo",
            pastParticiple: "yacido",
          },
          {
            infinitive: "estar acostado",
            presentIndicative: [
              "estoy acostado",
              "estás acostado",
              "está acostado",
              "estamos acostados",
              "estáis acostados",
              "están acostados",
            ],
            preterite: [
              "estuve acostado",
              "estuviste acostado",
              "estuvo acostado",
              "estuvimos acostados",
              "estuvisteis acostados",
              "estuvieron acostados",
            ],
            imperfect: [
              "estaba acostado",
              "estabas acostado",
              "estaba acostado",
              "estábamos acostados",
              "estabais acostados",
              "estaban acostados",
            ],
            future: [
              "estaré acostado",
              "estarás acostado",
              "estará acostado",
              "estaremos acostados",
              "estaréis acostados",
              "estarán acostados",
            ],
            conditional: [
              "estaría acostado",
              "estarías acostado",
              "estaría acostado",
              "estaríamos acostados",
              "estaríais acostados",
              "estarían acostados",
            ],
            presentSubjunctive: [
              "esté acostado",
              "estés acostado",
              "esté acostado",
              "estemos acostados",
              "estéis acostados",
              "estén acostados",
            ],
            imperfectSubjunctive: [
              "estuviera acostado",
              "estuvieras acostado",
              "estuviera acostado",
              "estuviéramos acostados",
              "estuvierais acostados",
              "estuvieran acostados",
            ],
            imperative: {
              tu: "estate acostado",
              usted: "esté acostado",
              nosotros: "estemos acostados",
              vosotros: "estad acostados",
              ustedes: "estén acostados",
            },
            gerund: "estando acostado",
            pastParticiple: "estado acostado",
          },
          {
            infinitive: "estar tumbado",
            presentIndicative: [
              "estoy tumbado",
              "estás tumbado",
              "está tumbado",
              "estamos tumbados",
              "estáis tumbados",
              "están tumbados",
            ],
            preterite: [
              "estuve tumbado",
              "estuviste tumbado",
              "estuvo tumbado",
              "estuvimos tumbados",
              "estuvisteis tumbados",
              "estuvieron tumbados",
            ],
            imperfect: [
              "estaba tumbado",
              "estabas tumbado",
              "estaba tumbado",
              "estábamos tumbados",
              "estabais tumbados",
              "estaban tumbados",
            ],
            future: [
              "estaré tumbado",
              "estarás tumbado",
              "estará tumbado",
              "estaremos tumbados",
              "estaréis tumbados",
              "estarán tumbados",
            ],
            conditional: [
              "estaría tumbado",
              "estarías tumbado",
              "estaría tumbado",
              "estaríamos tumbados",
              "estaríais tumbados",
              "estarían tumbados",
            ],
            presentSubjunctive: [
              "esté tumbado",
              "estés tumbado",
              "esté tumbado",
              "estemos tumbados",
              "estéis tumbados",
              "estén tumbados",
            ],
            imperfectSubjunctive: [
              "estuviera tumbado",
              "estuvieras tumbado",
              "estuviera tumbado",
              "estuviéramos tumbados",
              "estuvierais tumbados",
              "estuvieran tumbados",
            ],
            imperative: {
              tu: "estate tumbado",
              usted: "esté tumbado",
              nosotros: "estemos tumbados",
              vosotros: "estad tumbados",
              ustedes: "estén tumbados",
            },
            gerund: "estando tumbado",
            pastParticiple: "estado tumbado",
          },
        ],
        en: [
          {
            infinitive: "sleep",
            presentIndicative: [
              "sleep",
              "sleep",
              "sleeps",
              "sleep",
              "sleep",
              "sleep",
            ],
            preterite: ["slept", "slept", "slept", "slept", "slept", "slept"],
            imperfect: [
              "was sleeping",
              "were sleeping",
              "was sleeping",
              "were sleeping",
              "were sleeping",
              "were sleeping",
            ],
            future: [
              "will sleep",
              "will sleep",
              "will sleep",
              "will sleep",
              "will sleep",
              "will sleep",
            ],
            conditional: [
              "would sleep",
              "would sleep",
              "would sleep",
              "would sleep",
              "would sleep",
              "would sleep",
            ],
            presentSubjunctive: [
              "sleep",
              "sleep",
              "sleep",
              "sleep",
              "sleep",
              "sleep",
            ],
            imperative: {
              tu: "sleep",
              usted: "sleep",
              nosotros: "let's sleep",
              vosotros: "sleep",
              ustedes: "sleep",
            },
            gerund: "sleeping",
            pastParticiple: "slept",
          },
          {
            infinitive: "lie down",
            presentIndicative: [
              "lie down",
              "lie down",
              "lies down",
              "lie down",
              "lie down",
              "lie down",
            ],
            preterite: [
              "lay down",
              "lay down",
              "lay down",
              "lay down",
              "lay down",
              "lay down",
            ],
            imperfect: [
              "was lying down",
              "were lying down",
              "was lying down",
              "were lying down",
              "were lying down",
              "were lying down",
            ],
            future: [
              "will lie down",
              "will lie down",
              "will lie down",
              "will lie down",
              "will lie down",
              "will lie down",
            ],
            conditional: [
              "would lie down",
              "would lie down",
              "would lie down",
              "would lie down",
              "would lie down",
              "would lie down",
            ],
            presentSubjunctive: [
              "lie down",
              "lie down",
              "lie down",
              "lie down",
              "lie down",
              "lie down",
            ],
            imperative: {
              tu: "lie down",
              usted: "lie down",
              nosotros: "let's lie down",
              vosotros: "lie down",
              ustedes: "lie down",
            },
            gerund: "lying down",
            pastParticiple: "lain down",
          },
          {
            infinitive: "live",
            presentIndicative: [
              "live",
              "live",
              "lives",
              "live",
              "live",
              "live",
            ],
            preterite: ["lived", "lived", "lived", "lived", "lived", "lived"],
            imperfect: [
              "was living",
              "were living",
              "was living",
              "were living",
              "were living",
              "were living",
            ],
            future: [
              "will live",
              "will live",
              "will live",
              "will live",
              "will live",
              "will live",
            ],
            conditional: [
              "would live",
              "would live",
              "would live",
              "would live",
              "would live",
              "would live",
            ],
            presentSubjunctive: [
              "live",
              "live",
              "live",
              "live",
              "live",
              "live",
            ],
            imperative: {
              tu: "live",
              usted: "live",
              nosotros: "let's live",
              vosotros: "live",
              ustedes: "live",
            },
            gerund: "living",
            pastParticiple: "lived",
          },
          {
            infinitive: "be (paths, law etc.)",
            presentIndicative: ["am", "are", "is", "are", "are", "are"],
            preterite: ["was", "were", "was", "were", "were", "were"],
            imperfect: [
              "was being",
              "were being",
              "was being",
              "were being",
              "were being",
              "were being",
            ],
            future: [
              "will be",
              "will be",
              "will be",
              "will be",
              "will be",
              "will be",
            ],
            conditional: [
              "would be",
              "would be",
              "would be",
              "would be",
              "would be",
              "would be",
            ],
            presentSubjunctive: ["be", "be", "be", "be", "be", "be"],
            imperative: {
              tu: "be",
              usted: "be",
              nosotros: "let's be",
              vosotros: "be",
              ustedes: "be",
            },
            gerund: "being",
            pastParticiple: "been",
          },
        ],
      },
    },
  },
  adjectives: {
    manymak: {
      meaningKey: "adj.manymak",
      gup: "manymak",
      pos: "adjective",
      formsByLang: {
        es: ["bueno", "buena", "bien"],
        en: ["good"],
      },
      pluralFormsByLang: {
        es: ["buenos", "buenas", "bienes"],
        en: ["goods"],
      },
    },
    mol: {
      meaningKey: "adj.mol",
      gup: "mol",
      pos: "adjective",
      formsByLang: {
        es: ["negro", "marrón", "marron", "negra"],
        en: ["black", "brown"],
      },
      pluralFormsByLang: {
        es: ["negros", "marrónes", "marrones", "negras"],
        en: ["blacks", "browns"],
      },
    },
  },
};

for (const [key, entry] of Object.entries(LEXICON.verbs)) {
  const derived = entry.derived ?? (entry.derived = {});
  const fromOld = PAST_PARTICIPLE_ADJECTIVES[key];
  derived.pastParticipleAdjectives =
    fromOld ?? derived.pastParticipleAdjectives ?? { es: [], en: [] };
}
